name: Deploy Application

on: 
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t 04aj/backend .
      - name: Publish Image to docker hub
        run: docker push 04aj/backend:latest 
 
  deploy-server:
    needs: build-server
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull 04aj/backend:latest 
      - name: Delete old container
        run: docker rm -f backend-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' 04aj/backend
  
  build-client:
    needs: deploy-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t 04aj/frontend --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'  .
      - name: Publish Image to docker hub
        run: docker push 04aj/frontend:latest 
 
  deploy-client:
    needs: build-client
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull 04aj/frontend:latest 
      - name: Delete old container
        run: docker rm -f frontend-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name frontend-container 04aj/frontend